### PR TITLE
10x React Performance Blog Post

### PR DESCRIPTION
**Pull request by freddyrangel**

### CODE REVIEW

**Comment by freddyrangel** [comment]
Looks like this failed due to "access rights". I figure I don't have to worry about this right?

**Comment by zackify** [comment]
Looks good, couple minor spelling issues I can fix myself tomorrow if you don't. I'll merge after that's fixed. Don't worry about the test. Thanks for the post!

**Comment by freddyrangel** [comment]
Sure sounds good! Thanks!

**Comment by freddyrangel** [comment]
I took a second look and saw some glaring mistakes. I fixed a few of them right now.

**Comment by zackify** [comment]
First sentence: 'from 3 seconds to less that 200 milliseconds' can you proof read it once more? Sorry.

**Comment by freddyrangel** [comment]
ok. i think this is a little cleaner

**Comment by zackify** [comment]
Cleaned it up a tiny bit and posted, thanks!

**Pull request merged**
