### PR TITLE
new article: react and ag-grid

### PR DESCRIPTION
**Pull request by ceolter**

### CODE REVIEW

**Comment by ceolter** [comment]
this is failing due to server permissions??

**Comment by zackify** [comment]
You can ignore the failure. But I like to have people posting tutorial oriented things. If you could make your post more in depth I will merge it

**Comment by ceolter** [comment]
thanks @zackify. i've added to it and changed so that it's now a light tutorial. is this ok for inclusion, or do you want it changed more?

**Comment by zackify** [comment]
Looks good, thanks for updating it!

**Comment by ceolter** [comment]
Thank you :)

On 29 January 2016 at 15:28, Zach Silveira <notifications@github.com> wrote:

> Merged #32 <https://github.com/Legitcode/ReactJSNews/pull/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Legitcode/ReactJSNews/pull/32#event-531455724>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
When does it go live?


On 29 January 2016 at 15:28, Niall Crosby <niall.crosby@gmail.com> wrote:

> Thank you :)
>
> On 29 January 2016 at 15:28, Zach Silveira <notifications@github.com>
> wrote:
>
>> Merged #32 <https://github.com/Legitcode/ReactJSNews/pull/32>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Legitcode/ReactJSNews/pull/32#event-531455724>.
>>
>
>
>
> --
> --
>
> The information transmitted is intended only for the person or entity to
> which it is addressed and may contain confidential and/or privileged
> material. Statements and opinions expressed in this e-mail may not
> represent those of the sender. Any review, retransmission, dissemination or
> other use of, or taking of any action in reliance upon, this information by
> persons or entities other than the intended recipient is prohibited. If you
> received this in error, please contact the sender immediately and delete
> the material from any computer.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by zackify** [comment]
http://reactjsnews.com/react-and-ag-grid/ :)

**Comment by ceolter** [comment]
Excellent. Thank you.

On 29 January 2016 at 15:29, Zach Silveira <notifications@github.com> wrote:

> http://reactjsnews.com/react-and-ag-grid/ :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Legitcode/ReactJSNews/pull/32#issuecomment-176815753>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Pull request merged**
