### PR TITLE
Update 2016-01-03-NgRepeat-Equivalent-in-React.md

### PR DESCRIPTION
**Pull request by louy**
Fixed a typo in the react code

### CODE REVIEW

**Comment by louy** [comment]
@zackify that component clearly doesn't use state.

**Comment by zackify** [comment]
There isn't actually a typo here. You are supposed to pass items as a prop to the component.

**Comment by louy** [comment]
why then would you need `getInitialState`? if it's a prop you'd either use `propTypes` or `getDefaultProps`. I found that it's confusing to include `getIntialState` there as it's useless.

**Comment by zackify** [comment]
Sorry I misread the commit, that's what I get for checking github at 4am. I thought you were adding getInitialState. Oops :)

**Comment by zackify** [comment]
Thanks I put it back haha

**Comment by louy** [comment]
no worries. it happens :)

**Pull request merged**
