### PR TITLE
Using GraphQL with MongoDB: graffiti-mongoose

### PR DESCRIPTION
**Pull request by tothandras**
This is an extract from the [original blog post](https://blog.risingstack.com/graffiti-mongoose-mongodb-for-graphql/).

### CODE REVIEW

**Comment by zackify** [comment]
Is this an entry for the conference ticket? Either way thanks :)

**Comment by tothandras** [comment]
@zackify sure :)

**Comment by tothandras** [comment]
@zackify can you add a link to the original blog post on the website? thanks in advance! :)

**Comment by zackify** [comment]
Send a PR, might not be able to until later

**Comment by tothandras** [comment]
#19 here you go

**Pull request merged**
